# Generated by Django 5.0.14 on 2026-07-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(default="My Shop", max_length=200)),
                ("shop_address", models.TextField(blank=True, default="")),
                ("shop_phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "shop_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
                ),
                ("tax_name", models.CharField(default="VAT", max_length=50)),
                ("timezone", models.CharField(default="Africa/Nairobi", max_length=50)),
                ("low_stock_threshold", models.IntegerField(default=10)),
                ("reorder_level", models.IntegerField(default=5)),
                ("allow_negative_inventory", models.BooleanField(default=False)),
                ("invoice_prefix", models.CharField(default="INV-", max_length=10)),
                ("enable_credit_sales", models.BooleanField(default=True)),
                (
                    "default_credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=5000.0, max_digits=12
                    ),
                ),
                ("receipt_footer", models.TextField(blank=True, default="")),
                ("low_stock_alerts", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
