# Generated by Django 6.0.7 on 2026-07-09 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "Stock In"),
                            ("stock_out", "Stock Out"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                            ("damage", "Damage"),
                            ("theft", "Theft"),
                            ("expired", "Expired"),
                            ("return", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "quantity_change",
                    models.IntegerField(
                        help_text="Positive for inbound, negative for outbound"
                    ),
                ),
                ("balance_before", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "stock_movements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "movement_type"],
                        name="stock_movem_product_1c9b03_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="stock_movem_created_07bdcc_idx"
                    ),
                ],
            },
        ),
    ]
