# Generated by Django 6.0.7 on 2026-07-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("viewed", "Viewed"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("exported", "Exported"),
                            ("imported", "Imported"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource", "resource_id"],
                        name="audit_logs_resourc_b87535_idx",
                    ),
                    models.Index(
                        fields=["user", "action"], name="audit_logs_user_id_d685f3_idx"
                    ),
                ],
            },
        ),
    ]
